Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Areas/Admin/Controllers/PostsController.cs
using FA.JustBlog.Common.Constants;
using FA.JustBlog.Services.Category;
using FA.JustBlog.Services.Post;
using FA.JustBlog.Services.Tag;
using FA.JustBlog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class PostsController : Controller
	{
		private readonly IPostService _postService;
		private readonly ITagService _tagService;
		private readonly ICategoryService _categoryService;

		public PostsController(IPostService postService, ITagService tagService, ICategoryService categoryService)
		{
			this._postService = postService;
			this._tagService = tagService;
			this._categoryService = categoryService;
		}

		// GET: Admin/Posts
		[Authorize]
		public async Task<IActionResult> Index()
		{
			var model = await _postService.GetAllPosts();
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Latest()
		{
			var model = await _postService.GetLatestPosts(5);
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> MostViewed()
		{
			var model = await _postService.GetMostViewedPosts(5);
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Interesting()
		{
			var model = await _postService.GetMostInterestingPosts(5);
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Published()
		{
			var model = await _postService.GetPublishedPosts();
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Unpublished()
		{
			var model = await _postService.GetUnpublishedPosts();
			return View(model);
		}

		[Authorize(Roles = Role.BlogOwner + "," + Role.Contributor)]
		// GET: Admin/Posts/Create
		public async Task<IActionResult> CreateAsync()
		{
			ViewData["CategoriesId"] = await _categoryService.GetSelectListItems();
			ViewData["TagsId"] = await _tagService.GetSelectListItems();
			return View();
		}

		// POST: Admin/Posts/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = Role.BlogOwner + "," + Role.Contributor)]
		public async Task<IActionResult> Create([Bind("Title,ShortDescription,Meta,Published,CategoriesId,PostContent,TagId")] PostCreateVM posts)
		{
			if (ModelState.IsValid)
			{
				await _postService.AddPost(posts);
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoriesId"] = await _categoryService.GetSelectListItems();
			ViewData["TagsId"] = await _tagService.GetSelectListItems();
			return View(posts);
		}

		// GET: Admin/Posts/Edit/5
		[Authorize(Roles = Role.BlogOwner + "," + Role.Contributor)]
		public async Task<IActionResult> Edit(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var posts = await _postService.FindPostById(id.Value);
			if (posts == null)
			{
				return NotFound();
			}

			var model = new PostCreateVM();

			model.Title = posts.Title;
			model.ShortDescription = posts.ShortDescription;
			model.Meta = posts.Meta;
			model.Published = posts.Published;
			model.CategoriesId = posts.CategoriesId;
			model.TagId = posts.PostTags.Select(it => it.TagId).ToList();
			
			model.PostContent = posts.PostContent;

			ViewData["CategoriesId"] = await _categoryService.GetSelectListItems();
			ViewData["TagsId"] = await _tagService.GetSelectListItems();
			TempData["PostId"] = id;
			return View(model);
		}

		// POST: Admin/Posts/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = Role.BlogOwner + "," + Role.Contributor)]
		public async Task<IActionResult> Edit(Guid id, [Bind("Title,ShortDescription,Meta,Published,CategoriesId,PostContent,TagId")] PostCreateVM posts)
		{

			if (ModelState.IsValid)
			{
				try
				{
					await _postService.EditPost(posts, id);
					return RedirectToAction(nameof(Index));
				}
				catch (InvalidOperationException ex)
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoriesId"] = await _categoryService.GetSelectListItems();
			ViewData["TagsId"] = await _tagService.GetSelectListItems();
			TempData["PostId"] = id;
			return View(posts);
		}

		// GET: Admin/Posts/Delete/5
		[Authorize(Roles = Role.BlogOwner)]
		public async Task<IActionResult> Delete(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var posts = await _postService.FindPostById(id.Value);
			if (posts == null)
			{
				return NotFound();
			}

			return View(posts);
		}

		// POST: Admin/Posts/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = Role.BlogOwner)]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			var posts = await _postService.FindPostById(id);

			if (posts != null)
			{
				await _postService.DeletePost(id);
			}

			return RedirectToAction(nameof(Index));
		}
	}
}

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Controllers/CategoryController.cs
using FA.JustBlog.Services.Post;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
	public class CategoryController : Controller
	{
		private readonly IPostService _postService;

		public CategoryController(IPostService postService)
		{
			this._postService = postService;
		}

		public async Task<IActionResult> Index(string name)
		{
			var model = await _postService.GetPostsByCategory(name);
			TempData["catName"] = name;
			return View(model);
		}
	}
}

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Services.Post;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
	public class PostController : Controller
	{
		private readonly IPostService _postService;

		public PostController(IPostService postService)
		{
			this._postService = postService;
		}

		public async Task<IActionResult> Index()
		{
			var model = await _postService.GetPublishedPosts();
			return View(model);
		}

		public async Task<IActionResult> Details(int year, int month, string title)
		{
			var model = await _postService.GetPostsDetails(year, month, title);
			return View(model);
		}
	}
}

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Services.Post;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
	public class TagController : Controller
	{
		private readonly IPostService _postService;

		public TagController(IPostService postService)
		{
			this._postService = postService;
		}

		public async Task<IActionResult> Index(string name)
		{
			var model = await _postService.GetPostsByTag(name);
			TempData["tagName"] = name;
			return View(model);
		}
	}
}

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Views/Shared/_AboutMePartial.cshtml
<div class="card mb-3">
	<div class="row g-0">
		<div class="col-md-4">
			<img src="/img/about-bg.jpg" class="img-fluid rounded-start" alt="...">
		</div>
		<div class="col-md-8">
			<div class="card-body">
				<h5 class="card-title">About me</h5>
				<p class="card-text">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
				</p>
			</div>
		</div>
	</div>
</div>

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Views/Shared/_FooterPartial.cshtml
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <div class="small text-center text-muted fst-italic">Copyright &copy; Just Blog 2022</div>

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Just Blog</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/">Just Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @foreach (var item in unitOfWork.CategoriesRepository.GetAll())
                            {
                                <li><a class="dropdown-item" asp-controller="Category" asp-action="Index" asp-route-name="@item.Name">@item.Name</a></li>
                            }
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="Admin" asp-controller="Posts" asp-action="Index">Publisher</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @RenderBody()
            </div>
        </div>
    </div>
    <partial name="_AboutMePartial"></partial>
    <partial name="_ListPostPartial"></partial>
    <partial name="_PopularTagPartial"></partial>
    <!-- Footer-->
    <partial name="_FooterPartial"></partial>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
</body>
</html>

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Views/Shared/_ListPostPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="post-title">Latest Posts</h2>
            <hr class="my-4" />

            @foreach (var item in await unitOfWork.PostsRepository.GetLatestPosts(5))
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id">
                        <h2 class="post-title">@item.Title</h2>
                        <h3 class="post-subtitle">@item.ShortDescription</h3>
                    </a>
                    <p class="post-meta">
                        Posted
                        on @item.PostedOn.GetPrettyDate() with rate of @item.TotalRate from @item.ViewCount view(s)
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
        </div>

        <div class="col-lg-6">
            <h2 class="post-title">Most Viewed Posts</h2>
            <hr class="my-4" />

            @foreach (var item in await unitOfWork.PostsRepository.GetMostViewedPosts(5))
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id">
                        <h2 class="post-title">@item.Title</h2>
                        <h3 class="post-subtitle">@item.ShortDescription</h3>
                    </a>
                    <p class="post-meta">
                        Posted
                        on @item.PostedOn.GetPrettyDate() with rate of @item.TotalRate from @item.ViewCount view(s)
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
        </div>
    </div>
</div>

Assignments/EntityFramework/FA.JustBlog.Web/FA.JustBlog/Views/Shared/_PopularTagPartial.cshtml
<div class="container">
    <h2 class="post-title">Popular tags</h2>
    <div class="row text-right">
        @foreach (var item in unitOfWork.TagsRepository.GetAll())
        {
            <div class="col-1">
                <span class="badge bg-info"><a asp-controller="Tag" asp-action="Index" asp-route-name="@item.Name">@item.Name</a></span>
            </div>
        }
    </div>

</div>